export interface QuoteResponse {
  statusCode: number;
  message: string;
  pagination: Pagination;
  totalQuotes: number;
  data: Quote[];
}

export interface Quote {
  _id: string;
  quoteText: string;
  quoteAuthor: string;
  quoteGenre: QuoteGenre;
  __v: number;
}

export interface Pagination {
  currentPage: number;
  nextPage: number | null;
  totalPages: number;
}

export enum QuoteGenre {
  Age = 'age',
  Alone = 'alone',
  Amazing = 'amazing',
  Anger = 'anger',
  Anniversary = 'anniversary',
  Architecture = 'architecture',
  Art = 'art',
  Attitude = 'attitude',
  Beauty = 'beauty',
  Best = 'best',
  Birthday = 'birthday',
  Business = 'business',
  Car = 'car',
  Change = 'change',
  Communication = 'communication',
  Computers = 'computers',
  Cool = 'cool',
  Courage = 'courage',
  Dad = 'dad',
  Dating = 'dating',
  Death = 'death',
  Design = 'design',
  Diet = 'diet',
  Dreams = 'dreams',
  Education = 'education',
  Environmental = 'environmental',
  Equality = 'equality',
  Experience = 'experience',
  Failure = 'failure',
  Faith = 'faith',
  Family = 'family',
  Famous = 'famous',
  Fear = 'fear',
  Finance = 'finance',
  Fitness = 'fitness',
  Food = 'food',
  Forgiveness = 'forgiveness',
  Freedom = 'freedom',
  Friendship = 'friendship',
  Funny = 'funny',
  Future = 'future',
  Gardening = 'gardening',
  God = 'god',
  Good = 'good',
  Government = 'government',
  Graduation = 'graduation',
  Great = 'great',
  Happiness = 'happiness',
  Health = 'health',
  History = 'history',
  Home = 'home',
  Hope = 'hope',
  Humor = 'humor',
  Imagination = 'imagination',
  Inspirational = 'inspirational',
  Intelligence = 'intelligence',
  Jealousy = 'jealousy',
  Knowledge = 'knowledge',
  Leadership = 'leadership',
  Learning = 'learning',
  Legal = 'legal',
  Life = 'life',
  Love = 'love',
  Marriage = 'marriage',
  Medical = 'medical',
  Men = 'men',
  Mom = 'mom',
  Money = 'money',
  Morning = 'morning',
  Motivational = 'motivational',
  Movies = 'movies',
  Movingon = 'movingon',
  Music = 'music',
  Nature = 'nature',
  Parenting = 'parenting',
  Patience = 'patience',
  Patriotism = 'patriotism',
  Peace = 'peace',
  Pet = 'pet',
  Poetry = 'poetry',
  Politics = 'politics',
  Positive = 'positive',
  Power = 'power',
  Relationship = 'relationship',
  Religion = 'religion',
  Respect = 'respect',
  Romantic = 'romantic',
  Sad = 'sad',
  Science = 'science',
  Smile = 'smile',
  Society = 'society',
  Sports = 'sports',
  Strength = 'strength',
  Success = 'success',
  Sympathy = 'sympathy',
  Teacher = 'teacher',
  Technology = 'technology',
  Teen = 'teen',
  Thankful = 'thankful',
  Time = 'time',
  Travel = 'travel',
  Trust = 'trust',
  Truth = 'truth',
  War = 'war',
  Wedding = 'wedding',
}
